const images ={
    account: require('../../assets/Icons/account.png'),
    show:require('../../assets/Icons/show_pass.png'),
    hide:require('../../assets/Icons/hide_pass.png'),
    clear:require('../../assets/Icons/clear.png'),
    checked:require('../../assets/Icons/check.png'),
    unchecked:require('../../assets/Icons/un_check.png'),
    back:require('../../assets/Icons/back_white.png'),
    qr:require('../../assets/Icons/qrcode.png'),
    logo:require('../../assets/Images/logo.png'),
    logout: require('../../assets/Icons/logout.png'),
    noti: require('../../assets/Icons/bell.png'),
    money: require('../../assets/Icons/money.png'),
    shop: require('../../assets/Icons/shop.png'),
    buy: require('../../assets/Icons/buy.png'),
    buy_action: require('../../assets/Icons/buy_action.png'),
    cancel: require('../../assets/Icons/cancel.png'),
    cart: require('../../assets/Icons/cart.png'),
    cart_white: require('../../assets/Icons/cart_white.png'),
    cart_action: require('../../assets/Icons/cart_action.png'),
    home: require('../../assets/Icons/home.png'),
    home_action: require('../../assets/Icons/home_action.png'),
    info: require('../../assets/Icons/info.png'),
    info_action: require('../../assets/Icons/info_action.png'),
    sell: require('../../assets/Icons/sell.png'),
    sell_action: require('../../assets/Icons/sell_action.png'),
    wallet: require('../../assets/Icons/wallet.png'),
    wallet_action: require('../../assets/Icons/wallet_action.png'),
}
export default images;