import { FormField } from "../formField";

export const DATA_REGISTER: FormField[] = [
    {
        id: 1,
        title: 'Số CCCD/CMND',
        content: 'Số CCCD/CMND',
        isSecure: false,
        isQr:true,
        keyboardType: 'number-pad',
        require:true,
        type:1,
        data:null,
        isShowPass: false,
    },
    {
        id: 2,
        title: 'Họ và tên',
        content: 'Nhập họ và tên',
        isSecure: false,
        isQr:false,
        keyboardType: 'default',
        require:true,
        type:1,
        data:null,
        isShowPass: false,
    },
    {
        id: 3,
        title: 'Giới tính',
        content: 'Giới tính',
        isSecure: false,
        isQr:false,
        keyboardType: 'numeric',
        require:true,
        type:2,
        data:[
            {id:1, name:'Nam'},
            {id:2, name:'Nữ'},
        ],
        isShowPass: false,
    },
    {
        id: 4,
        title: 'Ngày sinh',
        content: 'Ngày sinh',
        isSecure: false,
        isQr:false,
        keyboardType: 'numeric',
        require:true,
        type:3,
        data:null,
        isShowPass: false,
    },
    {
        id: 5,
        title: 'Địa chỉ',
        content: 'Địa chỉ',
        isSecure: false,
        isQr:false,
        keyboardType: 'default',
        require:true,
        type:1,
        data:null,
        isShowPass: false,
    },
    {
        id: 6,
        title: 'Tên đăng nhập',
        content: 'Tên đăng nhập',
        isSecure: false,
        isQr:false,
        keyboardType: 'default',
        require:true,
        type:1,
        data:null,
        isShowPass: false,
    },
    {
        id: 7,
        title: 'Mật khẩu',
        content: 'Mật khẩu',
        isSecure: true,
        isQr:false,
        keyboardType: 'default',
        require:true,
        type:1,
        data:null,
        isShowPass: true,
    },
    {
        id: 8,
        title: 'Nhập lại mật khẩu',
        content: 'Nhập lại mật khẩu',
        isSecure: true,
        isQr:false,
        keyboardType: 'default',
        require:true,
        type:1,
        data:null,
        isShowPass: true,
    },
    {
        id: 9,
        title: 'Số điện thoại',
        content: 'Số điện thoại',
        isSecure: false,
        isQr:false,
        keyboardType: 'number-pad',
        require:true,
        type:1,
        data:null,
        isShowPass: false,
    },
    {
        id: 10,
        title: 'Email',
        content: 'Email',
        isSecure: false,
        isQr:false,
        keyboardType: 'email-address',
        require:true,
        type:1,
        data:null,
        isShowPass: false,
    },
    
];
export default DATA_REGISTER;
